name: "ChillyPig Laser Engraver"
board: "FluidNC Laser Engraver v1.1"

stepping:
  engine: RMT
  #The following settings are set to the defaults
  idle_ms: 250
  dir_delay_us: 0
  pulse_us: 4
  disable_delay_us: 0

uart1:
  txd_pin: gpio.17
  rxd_pin: gpio.16
  rts_pin: NO_PIN
  cts_pin: NO_PIN
  baud: 115200
  mode: 8N1

axes:
  shared_stepper_disable_pin: gpio.13:high
  
  x:
    steps_per_mm: 180
    max_rate_mm_per_min: 2000
    acceleration_mm_per_sec2: 25
    max_travel_mm: 400
    soft_limits: false
    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 200.000
      settle_ms: 200
      seek_scaler: 1.100
      feed_scaler: 1.100
    
    motor0:
      # External pull-up resistor used for limit switch
      limit_neg_pin: gpio.34:low
      #Diag pin is gpio.39
      tmc_2209:
        uart_num: 1
        addr: 0
        r_sense_ohms: 0.110
        run_amps: 0.100
        hold_amps: 0.500
        microsteps: 32
        stallguard: 0
        stallguard_debug: false
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: StealthChop
        homing_mode: StealthChop
        use_enable: false
        direction_pin: gpio.25
        step_pin: gpio.26
        disable_pin: NO_PIN
    
    motor1:
      null_motor:

  y:
    steps_per_mm: 180
    max_rate_mm_per_min: 2000
    acceleration_mm_per_sec2: 25
    max_travel_mm: 400
    soft_limits: false
    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 200.000
      settle_ms: 200
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      # External pull-up resistor used for limit switch
      limit_neg_pin: gpio.35:low
      #Diag pin is gpio.36
      tmc_2209:
        uart_num: 1
        addr: 1
        r_sense_ohms: 0.110
        run_amps: 1.500
        hold_amps: 0.500
        microsteps: 32
        stallguard: 0
        stallguard_debug: false
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: StealthChop
        homing_mode: StealthChop
        use_enable: false
        direction_pin: gpio.32
        step_pin: gpio.33
        disable_pin: NO_PIN
    motor1:
      null_motor:

  z:
    steps_per_mm: 100.000
    max_rate_mm_per_min: 1000.000
    acceleration_mm_per_sec2: 100.000
    max_travel_mm: 100.000
    soft_limits: false
    motor0:
      null_motor:
    motor1:
      null_motor:
        
spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  cs_pin: gpio.5
  card_detect_pin: NO_PIN
  frequency_hz: 1000000
  
coolant:
  # Coolant pins are controlled by GCODE M7, M8, & M9. They can be used for other purposes depending on the application.
  # These are included here with the intent to be used for an air assist. Software such as Lightburn can be configured to 
  # issue the GCODE command M8 for air assist. M7 = mist, M8 = Flood, M9 = Off
  mist_pin:  NO_PIN
  flood_pin: gpio.22
 
control:
  # External pull-up resistors used. If no external pull-ups, add :pu suffix to gpio definition
  feed_hold_pin: gpio.27:low:pu
  cycle_start_pin: gpio.14:low:pu
  
Laser:
  pwm_hz: 5000
  output_pin: gpio.4
  enable_pin: gpio.21:pd
  disable_with_s0: false
  s0_with_disable: true
  tool_num: 0
  speed_map: 0=0.000% 1000=100.000%
  off_on_alarm: true

